[project]
name = "flash-attn"
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["torch"]
version = "2.7.4.post1"
description = "Fast and memory-efficient exact attention"
license = "BSD-3-Clause"

[build-system]
requires = ["torch"]
build-backend = "setuptools.build_meta"
